### ISSUE TITLE
Pi Imager issues

### ISSUE THREAD

**Issue by Dustjed** [tesla-android/issue-tracker#173]
When using 2022.45.1 image with pi imager it just gives me Error extracting archive: File size could not be restored

**Comment by electricAntEater32** [comment]
This error seems to happen to people using Windows & the single image install method. You'll need a micros card larger than 32GB in order to use the single install method. Many Windows users have gotten around image writing errors by first unzipping the image. Then instruct the imager program to use the unzipped file.
@mikegapinski
