### ISSUE TITLE
Home/Work WiFi keeps disconnecting if Raspberry is left plugged in

### ISSUE THREAD

**Issue by tregan01** [tesla-android/issue-tracker#219]
If I leave the raspberry pi4 plugged in, I continuously get kicked off both my home and work wifi, and my iPhone with automatically connect to CarPlay, even though nothing is showing connected to the raspberry Pi4 (ie: Wifi or Bluetooth). If I disconnect it, my wifi connect works normally.

**Comment by adamChrystie** [comment]
The iPhone connects to the carlinkit dongle via wifi it doesn't connect to the raspberry pi via wifi. If you plan on leaving your raspberry pi plugged in all the time (I do not recommend this)  when you are not in the car and if you have sentry mode on, then the 12V power system will remain on all day and your carlinkit adapter will have power and connect to your iPhone via wifi. So you can go to iOS settings for CarPlay and turn off wireless CarPlay to stop this from happening. However, I really think you should just turn of the pie if you will not be using the car for long periods of time especially if your car is in the sun and just getting hot all day.

Just a guess regarding you getting booted of your home and work wifi, view the raspberry pi / Android OS  network settings and remove your home and work WIFI hotspots if you see entries. Also tell Mac computers to forget the Tesla android wifi network or edit to to disable "auto join"...maybe your computers are auto connecting to Tesla android because you used them for debugging? This happened to me once.

**Comment by tregan01** [comment]
Thank you for your reply. I have tried that. I have nothing set to Auto Join as far as the rpi4 is concerned, I have it connected to a USB port in the car, sentry mode is not on (so it shouldn't be getting any power). I have nothing showing that it is connected, yet I am in my office and still getting kicked off work's wifi

**Comment by mikegapinski** [comment]
When the car is awake(charging, alarm active or sentry) the usb ports are powered and the pi is on all the time. The only suggestion I have for now is unplugging the pi when you leave the car in public for a longer while. 

It'll be nicely automated at some point

**Comment by mikegapinski** [comment]
You can also disable auto start or auto join in auto kit settings, your phone won't automatically start CarPlay when you are near the car. 

One other thing worth checking out is disabling CarPlay in bluetooth settings on iOS. Just tap on the auto kit device and disable the CarPlay toggle. Switch it back when you want CarPlay to start automatically

**Comment by tregan01** [comment]
Thank you very much. I will definitely check it out. Although for now, it seems to be leaving me on my office wifi, so perhaps I just needed a little more patience to let the car power down? Ha! Ha! 

And thank you for creating the time to do this. Definitely a HUGE benefit to the car.
