### ISSUE TITLE
Lag between audio and video while streaming to MCU2

### ISSUE THREAD

**Issue by sw1002** [tesla-android/issue-tracker#227]
When I stream media on TeslaAndroid (e.g. prime video) even in low quality, I have a lag of approximately 1 second between audio and video, thus audio is being played back earlier than video. When streaming to a tablet even inside the car (e.g. ipad with firefox) both tracks (audio and video) are well aligned. Any idea how to fix this? Wifi Signal in MCU2 shows 4/4

**Comment by mikegapinski** [comment]
Place the pi near the Wi-Fi antenna in the car, right rear view mirror in older cars. Pillar over the center console in newer ones. 

There is zero synchronisation between the tracks at the moment since the browser is not actually playing video(Tesla limitation). Expect this to improve at some point but I doubt it will be perfect.

I could make browser audio configurable; you could disable it and pair the pi with the car via Bluetooth for streaming Netflix etc.

BTW: it has nothing to with the quality of the media you play; it's hardware accelerated anyways
