### ISSUE TITLE
I want to integrate these features on other devices

### ISSUE THREAD

**Issue by lcy0828** [tesla-android/issue-tracker#232]
How can I implement the main functions on other devices, such as old Android phones, by installing the AOSP system, and the phone has root permissions

**Comment by lcy0828** [comment]
Like some old mobile phones, they are equipped with Snapdragon 845 and other processors, which are much better in performance than Raspberry Pi 4b. At the same time, they can also perform flashing operations. Can you provide a compatible solution? Android system, on such a device, you can insert a card, or connect to CarlinKit through Autokit software.

**Comment by mikegapinski** [comment]
Assuming your device can run Android 13 all you need to do is add the device config to my AOSP fork and make sure it builds. Needs to be done individually for every phone, there are some kernel changes needed also. Tesla Android does not ship rooted(Magisk etc), all the changes are done directly in the frameworks itself using APIs that are not available for regular apps. 

BTW: There is almost zero bottleneck on the pi side at this point. You won't get more performance with another SOC, there is a technical limitations in the virtual display implementation itself. It's not a regular video stream, those do not work in drive. My workaround is good enough to make it usable but there are side effects. The approach I used is not efficient in terms of bandwidth but there is not a lot of extra latency. If you use another format (h264, blocked by tesla) you would get a smoother refresh rate but there will be much less responsive since there is some processing delay introduced by the encode/decode. 

Even if you get yourself a Snapdragon phone it'll throttle at some point, as it was not designed for constant load. The pi with a decent active cooler would perform better on longer drives. I've left mine on for 8h or more when doing a road trip. Zero problems, it took me a year to get it optimized...
