### ISSUE TITLE
HTTPS access stopped working suddendly and no GPS or browser audio on HTTP access

### ISSUE THREAD

**Issue by bpresles** [tesla-android/issue-tracker#308]
**Summary**

Since today, november 12th, the https://device.teslaandroid.com is not working (and fullscreen version either), it gets a security screen unable to pass with NET::ERR_CERT_DATE_INVALID error on chrome based browser.

Accessing via HTTP works but without GPS or browser audio, because of CORS issues (logical)

**Steps to reproduce**

Install Tesla Android version 2023.42.2

Boot the Tesla Android device (ex: Raspberry Pi 4)
Try to access https://device.teslaandroid.com

**Observed behavior**

Using HTTPS at first the screen stayed blank (white) and after clearing the Tesla browser data it displays a security screen saying NET::ERR_CERT_DATE_INVALID, indicating that the SSL certificate has probably expired.
On a Chrome browser on a computer, this also displays the security screen with NET::ERR_CERT_DATE_INVALID error.

I tried accessing the device using HTTP, but in that case browser audio and GPS don't work because of CORS issues, so it's not a viable option.

**Expected behavior**

Accessing the device through HTTPS works with both GPS and browser audio working.

**Comment by mikegapinski** [comment]
It is fixed already, the build will be live in a few

**Comment by miaszh** [comment]
> It is fixed already, the build will be live in a few

Hi, I have the exact same problem.. cannot access since few days ago.
Any help appreciated

Thanks

**Comment by mikegapinski** [comment]
Please install the update from last Friday

Od: miaszh ***@***.***>
Data: poniedziałek, 12 lutego 2024 o 07:55
Do: tesla-android/issue-tracker ***@***.***>
DW: Michał Gapiński ***@***.***>, State change ***@***.***>
Temat: Re: [tesla-android/issue-tracker] HTTPS access stopped working suddendly and no GPS or browser audio on HTTP access (Issue #308)

It is fixed already, the build will be live in a few

Hi, I have the exact same problem.. cannot access since few days ago.
Any help appreciated

Thanks
