### ISSUE TITLE
Interference between the original tesla Phone built in and Linux PI3

### ISSUE THREAD

**Issue by galosre** [tesla-android/issue-tracker#70]
So basically I was testing the navigation and music playing thru android auto everything good no complaint there. The issue rise if I want to use either Tu-in 's stations or the steaming app from Tesla no sound at all and the icons became generic. And I am getting spinning wheel like if I was in a zone of no phone reception, If I disconnect the wifi got sound for 5 Mn until I unplug the PI3 completely, and then everything become normal again.
 I thought at the beginning It was  Bluetooth related since I had so many issue about pairing, but mostly I had to reboot my phone and do pairing again between car and cp 200 specially this one is connected to the android one.
![2022-07-13_125452](https://user-images.githubusercontent.com/22267106/178822572-c9f01ee9-3493-42c3-a209-c5899abd7c4c.jpg)

**Comment by mikegapinski** [comment]
That is related to the offline mode in 2022.27.1. When Tesla Android is connected to the car Tesla OS wants to route connectivity through it.

That is expected, connectivity from Tesla system (especially premium connectivity features) do not function properly when the persistent connectivity bypass is enabled on the Tesla Android network.

My advice - don’t use the Tesla Android Wi-Fi network when not using the app in the browser. I doubt that Tesla will patch the system in order to allow normal connectivity to “offline” access to Wi-Fi networks.


Given that the current bypass is a first iteration of the “hack” I plan on improving how it works, but there is only so much I can do 🥲

**Comment by mikegapinski** [comment]
tunein will work when connected to the Tesla-Android Wi-Fi ONLY when there is an LTE stick present. No way around that unless Tesla changes their policy on how Wi-Fi works. 

All of the builtin apps that won't work alongside Tesla Android have their Android Auto or CarPlay replacements that use your smartphone's data.

If you want connectivity in both Tesla Android and Tesla main OS you need to get a data pack for the stick and cancel the premium connectivity subscription from Tesla

**Comment by galosre** [comment]
Not sure if I understand my LTE sd card got Data what am I  supposed to do I f I plug it back will, it work ?

FYI yesterday without the stick of course i succeed for a whole drive to get the premium working and android auto not sure how I did (maybe cancel/reconnect the CP 200)  but for that drive everything was working got Waze voice my music server ,and CNN
I will try to reproduce it and in this case I would pay attention the exact course of action in order to describe it

**Comment by mikegapinski** [comment]
Hmm… maybe it’s DNS.

try like this.

1. Turn off your Wi-Fi in the car.
2. Turn on TuneIn, start listening to music 
3. Wait a minute
4. Connect to Tesla-Android Wi-Fi
5. Use Android Auto

if it works like this I might have an idea what can I do to make it work.

**Comment by mikegapinski** [comment]
And yes, tunein, Spotify etc work with the LTE stick.
